const args = require('minimist')(process.argv.slice(2));

const siteUrl = args.siteUrl || 'https://beta.nhs.uk/find-a-pharmacy/';

module.exports = [
  {
    clickSelector: '',
    cookiePath: 'backstop_data/engine_scripts/cookies.json',
    delay: 0,
    expect: 0,
    hideSelectors: [],
    hoverSelector: '',
    label: 'search page',
    misMatchThreshold: 0.1,
    postInteractionWait: 0,
    readyEvent: '',
    readySelector: '',
    referenceUrl: '',
    removeSelectors: [],
    requireSameDimensions: true,
    selectorExpansion: true,
    selectors: [],
    url: siteUrl,
  },
  {
    clickSelector: '',
    cookiePath: 'backstop_data/engine_scripts/cookies.json',
    delay: 2000,
    expect: 0,
    hideSelectors: [],
    hoverSelector: '',
    label: 'results page',
    misMatchThreshold: 0.1,
    postInteractionWait: 0,
    readyEvent: '',
    readySelector: '',
    referenceUrl: '',
    removeSelectors: [],
    requireSameDimensions: true,
    selectorExpansion: true,
    selectors: [],
    url: `${siteUrl}results?location=Liverpool&open=false`,
  },
  {
    clickSelector: '',
    cookiePath: 'backstop_data/engine_scripts/cookies.json',
    delay: 2000,
    expect: 0,
    hideSelectors: [],
    hoverSelector: '',
    label: "we can't find page",
    misMatchThreshold: 0.1,
    postInteractionWait: 0,
    readyEvent: '',
    readySelector: '',
    referenceUrl: '',
    removeSelectors: [],
    requireSameDimensions: true,
    selectorExpansion: true,
    selectors: [],
    url: `${siteUrl}results?location=Glasgow&open=false`,
  },
];
